# SPDX-FileCopyrightText: 2024 Benedikt Franke <benedikt.franke@dlr.de>
# SPDX-FileCopyrightText: 2024 Florian Heinrich <florian.heinrich@dlr.de>
#
# SPDX-License-Identifier: Apache-2.0

[project]
# This is the name of your project. The first time you publish this
# package, this name will be registered for you. It will determine how
# users can install this project, e.g.:
#
# $ pip install sampleproject
#
# And where it will live on PyPI: https://pypi.org/project/sampleproject/
#
# There are some restrictions on what makes a valid project name
# specification here:
# https://packaging.python.org/specifications/core-metadata/#name
name = "dlr-logging"  # Required

# Versions should comply with PEP 440:
# https://www.python.org/dev/peps/pep-0440/
#
# For a discussion on single-sourcing the version, see
# https://packaging.python.org/guides/single-sourcing-package-version/
version = "0.0.4.dev0"  # Required

# This is a one-line description or tagline of what your project does. This
# corresponds to the "Summary" metadata field:
# https://packaging.python.org/specifications/core-metadata/#summary
description = "Logging Base Module"  # Optional

# This is an optional longer description of your project that represents
# the body of text which users will see when they visit PyPI.
#
# Often, this is the same as your README, so you can just read it in from
# that file directly (as we have already done above)
#
# This field corresponds to the "Description" metadata field:
# https://packaging.python.org/specifications/core-metadata/#description-optional
readme = "README.md" # Optional

# Specify which Python versions you support. In contrast to the
# 'Programming Language' classifiers above, 'pip install' will check this
# and refuse to install the project if the version does not match. See
# https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires
requires-python = ">=3.7"

# This is either text indicating the license for the distribution, or a file
# that contains the license
# https://packaging.python.org/en/latest/specifications/core-metadata/#license
license = {file = "LICENSES/Apache-2.0.txt"}

# This field adds keywords for your project which will appear on the
# project page. What does your project relate to?
#
# Note that this is a list of additional keywords, separated
# by commas, to be used to assist searching for the distribution in a
# larger catalog.
keywords = ["logging", "logger"]  # Optional

# This should be your name or the name of the organization who originally
# authored the project, and a valid email address corresponding to the name
# listed.
authors = [  # Optional
  {name="Benedikt Franke", email="benedikt.franke@dlr.de"},
  {name="Florian Heinrich", email="florian.heinrich@dlr.de"},
]

# This should be your name or the names of the organization who currently
# maintains the project, and a valid email address corresponding to the name
# listed.
maintainers = [  # Optional
  # {name="Jane Doe", email="jane.doe@example.com"}
]

# Classifiers help users find your project by categorizing it.
#
# For a list of valid classifiers, see https://pypi.org/classifiers/
classifiers = [  # Optional
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 3 - Alpha",

  # Indicate who your project is intended for
  "Operating System :: OS Independent",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",

  # Pick your license as you wish
  "License :: OSI Approved :: Apache Software License",

  # Specify the Python versions you support here. In particular, ensure
  # that you indicate you support Python 3. These classifiers are *not*
  # checked by "pip install". See instead "python_requires" below.
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
]

# This field lists other packages that your project depends on to run.
# Any package you put here will be installed by pip when your project is
# installed, so they must be valid existing projects.
#
# For an analysis of this field vs pip's requirements files see:
# https://packaging.python.org/discussions/install-requires-vs-requirements/
dependencies = [ # Optional
  "ansi~=0.3.6",
  "PyYAML~=6.0.1",
]

# List additional groups of dependencies here (e.g. development
# dependencies). Users will be able to install these using the "extras"
# syntax, for example:
#
#   $ pip install ".[all]"
#
# Similar to `dependencies` above, these must be valid existing
# projects.
[project.optional-dependencies] # Optional
dev = [
  "reuse~=3.0.2",
  "tox~=4.5.1",
]
test = [
  "autopep8~=2.0.2",
  #"coverage~=7.2.7",
  "flake8~=6.0.0",
  "flake8-pyproject~=1.2.3",
  "licensecheck",  # no version, install latest version
  "mypy~=1.3.0",
  #"pytest~=7.4.0",
  "shellcheck-py~=0.9.0.6",
]
stubs = [
  "types-PyYAML~=6.0.12.12"
]
doc = [
  "portray @ git+https://github.com/HeinrichAD/portray.git@v1.8.0-dev",
  #"plantuml-markdown~=3.9.2",  # post-install: cp plantuml_markdown.py into markdown/extensions
]
all = ["dlr-logging[dev,test,stubs,doc]"]

# List URLs that are relevant to your project
#
# This field corresponds to the "Project-URL" and "Home-Page" metadata fields:
# https://packaging.python.org/specifications/core-metadata/#project-url-multiple-use
# https://packaging.python.org/specifications/core-metadata/#home-page-optional
#
# Examples listed include a pattern for specifying where the package tracks
# issues, where the source is hosted, where to say thanks to the package
# maintainers, and where to support the project financially. The key is
# what's used to render the link text on PyPI.
[project.urls]  # Optional
"Homepage" = "https://github.com/DLR-KI/fl-logging-base"
"Bug Tracker" = "https://github.com/DLR-KI/fl-logging-base/issues"
#"Changelog" = "https://github.com/DLR-KI/fl-logging-base/blob/main/CHANGELOG.md"
#"Funding" = "https://donate.pypi.org"
#"Say Thanks!" = "https://saythanks.io/to/dlr-logging"
"Source" = "https://github.com/DLR-KI/fl-logging-base"

# The following would provide a command line executable called `fl-template`
# which executes the function `main` inside `__main__.py` from this package when invoked.
#[project.scripts]  # Optional
#dlr-logging = "dlr.ki.logging.__main__:main"

# This is configuration specific to the `setuptools` build backend.
# If you are using a different build backend, you will need to change this.
[tool.setuptools]
# If there are data files included in your packages that need to be
# installed, specify them here.
packages = ["dlr.ki.logging", "dlr.ki.logging.formatter"]
package-data = {"dlr.ki.logging" = ["py.typed"]}
license-files = ["LICENSES/*.txt"]

[build-system]
# These are the assumed default build requirements from pip:
# https://pip.pypa.io/en/stable/reference/pip/#pep-517-and-518-support
requires = ["setuptools>=43.0.0", "wheel"]
build-backend = "setuptools.build_meta"

#######################################################################################################################

# licensecheck
# https://github.com/FHPythonUtils/LicenseCheck/blob/master/README.md

[tool.licensecheck]
using = "PEP631"
#using = "PEP631:dev;test;stubs;doc"
zero = true

#######################################################################################################################

# flake8
# https://flake8.pycqa.org/en/latest/user/configuration.html

[tool.flake8]
max-line-length = 120
per-file-ignores = [
  "__init__.py: F401",
]
exclude = [
  ".build",
  ".git",
  ".github",
  ".*_cache",
  ".tox",
  ".venv",
  ".vscode",
  "*.egg",
  "*.egg-info",
  "__pycache__",
  "Interactive-1.interactive",
]
#select = "E,W,F"

#######################################################################################################################

# mypy
# https://mypy.readthedocs.io/en/stable/config_file.html

[tool.mypy]
# Global options
no_implicit_optional = true
show_error_codes = true
#warn_return_any = true
#warn_unused_configs = true
#disallow_untyped_defs = true

# Per-module options

# Ignore missing imports (missing stubs or py.typed)
[[tool.mypy.overrides]]
module = [
  "setuptools.*",
]
ignore_missing_imports = true

#######################################################################################################################

# coverage
# https://coverage.readthedocs.io/en/latest/config.html

[tool.coverage.run]
branch = true
source = "dlr.ki.logging"

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
  # Have to re-enable the standard pragma
  "pragma: no cover",
  "@overload",

  # Don't complain about missing debug-only code:
  "def __repr__",
  "if self\\.debug",

  # Don't complain if tests don't hit defensive assertion code:
  "raise AssertionError",
  "raise NotImplementedError",

  # Don't complain if non-runnable code isn't run:
  "if 0:",
  "if Flase:",
  "if __name__ == .__main__.:",

  # Don't complain about abstract methods, they aren't run:
  "@(abc\\.)?abstractmethod",
]

ignore_errors = true
skip_empty = true

[tool.coverage.html]
title = "Coverage report for dlr.ki.logging"

#######################################################################################################################

# pytest
# https://docs.pytest.org/en/latest

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
